config/routes.rb
LogJam::Application.routes.draw do
  get "/stats/systems", to: 'log_stats#systems', as: :systems
  
  delete '/ops/clear-index', to: 'log_stats#clear_index', as: :clear_index

  get "/facets", to: 'log_view#facets', as: :facets
  
  get '/poll', to: 'log_view#poll', as: :poll

  root 'log_view#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def es_client
    @es_client ||= Elasticsearch::Client.new log: false, hosts: "#{SETTINGS['elasticsearch']['host']}:#{SETTINGS['elasticsearch']['port']}"
  end

  def es_index
    @es_index ||= Time.zone.now.utc.strftime SETTINGS['elasticsearch']['index_format']
  end

end

app/controllers/log_stats_controller.rb
class LogStatsController < ApplicationController
  def systems
    response = es_client.search index: es_index, body: {
      facets: { tag: { terms: { field: "tag"} } }
    }

    stats_resp = es_client.indices.stats index: es_index

    resp = {
      facets: response['facets']['tag']['terms'],
      total_lines: stats_resp['_all']['primaries']['docs']['count'],
      #other: stats_resp
    }
    render json: resp
  rescue Elasticsearch::Transport::Transport::Errors::NotFound
    render json: {status: 404}, status: 404
  end


  def clear_index
    es_client.indices.delete index: es_index
  ensure
    redirect_to root_path
  end
end

app/controllers/log_view_controller.rb
class LogViewController < ApplicationController
  def index

    @settings = {
      elasticsearch_address: "#{SETTINGS['elasticsearch']['host']}:#{SETTINGS['elasticsearch']['port']}",
      refresh_logs: SETTINGS['refresh_logs'].to_i,
      batch_size: SETTINGS['batch_size'].to_i
    }

    render layout: 'base'
  end

  def poll
    batch_size = params[:size] || SETTINGS['batch_size']
    from = params[:from] || "0"

    query = {
      sort: [{"@timestamp" => {order: 'asc'}}],
      size: batch_size.to_i,
      from: from.to_i,
      fields: ['@timestamp', 'tag', 'message'],
      explain: false
    }

    if params[:q].present? && params[:q].size > 0
      query[:query] = {
        query_string: {
          default_field: "message",
          query: params[:q]
        }
      }
    end

    if params[:system].present?
      query[:post_filter] = {
        term: { 
          tag: params[:system] 
        }
      }
    end

    response = es_client.search index: es_index, body: query

    render json: response

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
- content_for :content do
  div class="container"
    = yield
= render template: 'layouts/base'

app/views/layouts/base.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8" /
    meta http-equiv="X-UA-Compatible" content="IE=edge" /
    meta name="viewport" content="width=device-width, initial-scale=1.0" /
    meta name="description" content="" /
    meta name="author" content="" /
    / <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

    title
      | Log Jam
    = csrf_meta_tags

    / Bootstrap core CSS 
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true

    = javascript_include_tag "application"

  body

    div class="navbar navbar-inverse navbar-fixed-top" role="navigation"
      div class="navbar-header"
        button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"
          span class="sr-only" Toggle navigation
          span class="icon-bar"
          span class="icon-bar"
          span class="icon-bar"
        = link_to 'Log Jam', '#', class: 'navbar-brand'

      div class="navbar-collapse collapse"
        ul class="nav navbar-nav"
          li
            = link_to 'Home', '#'
        p class="navbar-text navbar-right" id="network-indicator" style="display:none;"
          | Loading...
        / ul class="nav navbar-nav navbar-right"
        /   li
        /     = link_to 'Sign Out', '#', method: :delete
        
    = content_for?(:content) ? yield(:content) : yield

app/views/log_view/index.html.slim
div class='log-terminal'
  div class="log-info-message" style="display:none;"
    | Problem

div class='log-dashboard'
  div class="row"
    div class="col-md-4 search-box"
      input type="text" name="search" id="search" placeholder="Search..." /
      ' 
      a href="#clear" class='clear-search' Clear
    div class="col-md-7"
      div id="facets"
    div class="col-md-1"
      a href="#follow" data-log-action="tail" Follow
      br /
      = link_to 'Clear Index', clear_index_path, method: :delete, data: {confirm: 'Are you sure? This will wipe out the elastic search index'}

javascript:
  var logview = new LogView(#{@settings.to_json.html_safe})